baseURL = 'https://jackd1801.github.io/'
languageCode = 'en-us'
title = 'jackbduncan'
theme = 'ananke'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Navigation menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 15
  [[menu.main]]
    identifier = "writing"
    name = "Writing"
    url = "/writing"
    weight = 30
  [[menu.main]]
    identifier = "recommendations"
    name = "Recommendations"
    url = "/recommendations"
    weight = 45
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 60
  [[menu.main]]
    identifier = "pictures"
    name = "Pictures"
    url = "/pictures"
    weight = 75