baseURL = 'https://jackd1801.github.io/'
languageCode = 'en-us'
title = 'jackbduncan'
theme = 'jack-custom-theme'

[menu]
  [[menu.main]]
    indentifier = "home"
    name="Home"
    url="/"
    weight=1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 15

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 30

  [[menu.main]]
    identifier = "media"
    name = "Media"
    url = "/media"
    weight = 45

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 60

  [[menu.main]]
    identifier = "photos"
    name = "Photos"
    url = "/photos"
    weight = 75